name: Deploy FastAPI BAckend to EC2

on:
  push:
    branches:
      -main 

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Setup SSH for EC2 connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Update backend environment file(.env)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "${{ secrets.BACKEND_ENV }}" > /var/www/Elden-ATS/Backend-ATS/.env
          EOF

      - name: Deploy and restart backend oEC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/Elden-ATS/Backend-ATS
          echo " puliing latest code "
          git pull origin main
          echo " Activating virtual environment "
          source /var/www/Elden-ATS/Backend-ATS/.venv/bin/activate
          echo " Installing dependencies "
          pip install -r /var/www/Elden-ATS/Backend-ATS/requirements.txt 
          echo " restarting backend services "
          sudo systemctl restart ats-backend
          echo " deployment cimoleted successfully"
          EOF
