name: Deploy FastAPI Backend to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Copy code to EC2 via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/var/www/Elden-ATS/Backend-ATS"

      - name: SSH and restart backend service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /var/www/Elden-ATS/Backend-ATS

            if [ -f .env ]; then
              cp .env .env.backup.$(date +%Y%m%d_%H%M%S)
            fi

            echo "${{ secrets.BACKEND_ENV }}" > .env

            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi

            source .venv/bin/activate
            pip install --upgrade pip --quiet

            if [ -f requirements.txt ]; then
              pip install --no-cache-dir -r requirements.txt --quiet
            fi

            sudo systemctl restart ats-backend
            sleep 3

            if sudo systemctl is-active --quiet ats-backend; then
              if ! (curl -s http://127.0.0.1:8000 > /dev/null || curl -s http://127.0.0.1:8000/docs > /dev/null); then
                exit 1
              fi
            else
              sudo journalctl -u ats-backend -n 50 --no-pager
              exit 1
            fi
