name: Deploy FastAPI Backend to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Deploy and restart backend on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/Elden-ATS/Backend-ATS

            # Update environment file
            echo "${{ secrets.BACKEND_ENV }}" > .env

            # Get latest code
            git fetch origin main
            git reset --hard origin/main

            # Activate virtual environment & install dependencies
            source /var/www/Elden-ATS/Backend-ATS/.venv/bin/activate
            pip install --no-cache-dir -r requirements.txt

            # Restart backend service
            sudo systemctl restart ats-backend
