name: Deploy FastAPI Backend to EC2

on:
  push:
    branches:
      - main  # Trigger deployment whenever code is pushed to the main branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from your repo
      - name: Checkout latest code
        uses: actions/checkout@v3

      # Setup SSH key to connect to EC2 securely
      - name: Setup SSH for EC2 connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # (Recommended) Update .env file automatically on the server
      - name: Update backend environment file (.env)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "${{ secrets.BACKEND_ENV }}" > /var/www/Elden-ATS/Backend-ATS/.env
          EOF

      # Deploy and restart the backend service
      - name: Deploy and restart backend on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/Elden-ATS/Backend-ATS
          echo "Pulling latest code..."
          git pull origin main
          echo "Activating virtual environment..."
          source /var/www/Elden-ATS/Backend-ATS/.venv/bin/activate
          echo "Installing dependencies..."
          pip install -r requirements.txt
          echo "Restarting backend service..."
          sudo systemctl restart ats-backend
          echo "Deployment completed successfully!"
          EOF
