name: Deploy FastAPI Backend to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Copy backend files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "/var/www/Elden-ATS/Backend-ATS"

      - name: Run backend setup and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: false
          script: |
            set -e

            cd /var/www/Elden-ATS/Backend-ATS

            # Create new .env from GitHub secret
            echo "${{ secrets.BACKEND_ENV }}" > .env

            # Create virtual environment if not exists
            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi

            source .venv/bin/activate
            pip install --upgrade pip --quiet

            # Install dependencies
            if [ -f requirements.txt ]; then
              pip install --no-cache-dir -r requirements.txt --quiet
            fi

            # Run Alembic migrations
            if [ -d "migrations" ] || [ -d "alembic" ]; then
              alembic upgrade head
            fi

            # Restart backend service
            sudo systemctl restart ats-backend
